language: php
# cache: yarn
php:
  - 7.1
install:
  - travis_retry composer install
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit
after_success:
  - travis_retry php vendor/bin/php-coveralls -v